-- Schema inicial do PoeNaLista. Documentação: docs/modelo-de-dados.md
-- SQL compatível com PostgreSQL e com H2 em modo PostgreSQL.

CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100)             NOT NULL,
    email          VARCHAR(255)             NOT NULL,
    password_hash  VARCHAR(255)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE houses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)             NOT NULL,
    created_by  BIGINT                   NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_houses_created_by FOREIGN KEY (created_by) REFERENCES users (id)
);

CREATE TABLE residents (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id   BIGINT                   NOT NULL,
    user_id    BIGINT                   NOT NULL,
    role       VARCHAR(20)              NOT NULL,
    joined_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_residents_house FOREIGN KEY (house_id) REFERENCES houses (id) ON DELETE CASCADE,
    CONSTRAINT fk_residents_user  FOREIGN KEY (user_id)  REFERENCES users (id),
    CONSTRAINT uk_residents_house_user UNIQUE (house_id, user_id),
    CONSTRAINT ck_residents_role CHECK (role IN ('MODERATOR', 'MEMBER'))
);

CREATE INDEX ix_residents_user ON residents (user_id);

CREATE TABLE invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id    BIGINT                   NOT NULL,
    code        VARCHAR(20)              NOT NULL,
    created_by  BIGINT                   NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_invites_house      FOREIGN KEY (house_id)   REFERENCES houses (id) ON DELETE CASCADE,
    CONSTRAINT fk_invites_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT uk_invites_code UNIQUE (code)
);

CREATE TABLE shopping_lists (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    house_id    BIGINT                   NOT NULL,
    name        VARCHAR(100)             NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_shopping_lists_house FOREIGN KEY (house_id) REFERENCES houses (id) ON DELETE CASCADE,
    CONSTRAINT uk_shopping_lists_house_name UNIQUE (house_id, name)
);

CREATE TABLE categories (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shopping_list_id  BIGINT                   NOT NULL,
    category_id       BIGINT,
    name              VARCHAR(100)             NOT NULL,
    quantity          INTEGER                  NOT NULL DEFAULT 1,
    status            VARCHAR(20)              NOT NULL DEFAULT 'PENDING',
    added_by          BIGINT                   NOT NULL,
    bought_by         BIGINT,
    bought_at         TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_items_shopping_list FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists (id) ON DELETE CASCADE,
    CONSTRAINT fk_items_category      FOREIGN KEY (category_id)      REFERENCES categories (id),
    CONSTRAINT fk_items_added_by      FOREIGN KEY (added_by)         REFERENCES users (id),
    CONSTRAINT fk_items_bought_by     FOREIGN KEY (bought_by)        REFERENCES users (id),
    CONSTRAINT ck_items_status CHECK (status IN ('PENDING', 'BOUGHT')),
    CONSTRAINT ck_items_quantity CHECK (quantity > 0)
);

CREATE INDEX ix_items_shopping_list_status ON items (shopping_list_id, status);
